version: '3.8'

services:

  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    image: todo-app:latest
    restart: unless-stopped
    container_name: todo-app
    hostname: todo-app
    ports:
      - "80:8080"
    networks:
      - todo-net

  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: todo-db
    hostname: todo-db
    environment:
      POSTGRES_DB: todo-postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - todo-net

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    container_name: pgAdmin
    hostname: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: adm@test.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 8081:80
    networks:
      - todo-net

networks:
  todo-net:
