version: '3.8'

services:

  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: todo-db
    hostname: todo-db
    environment:
      POSTGRES_DB: todo-postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - db-network

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    container_name: pgAdmin
    hostname: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: adm@test.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 8081:80
    networks:
      - db-network

networks:
  db-network:
